# Generated by Django 2.2.6 on 2019-10-22 02:31

import WebBoxFashion.apps.security.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.CharField(max_length=150, verbose_name='Contraseña')),
                ('contrasenia', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('is_active', models.BooleanField(verbose_name='Activacion del Cliente')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Login Cliente',
                'verbose_name_plural': 'Login Clientes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Quiz_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cod_quiz', models.IntegerField()),
                ('cod_iso_quiz', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to=WebBoxFashion.apps.security.models.UserProfile.image_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotype', models.IntegerField()),
                ('number_shirt', models.IntegerField()),
                ('number_pants', models.IntegerField()),
                ('number_height', models.IntegerField()),
                ('number_weight', models.IntegerField()),
                ('sex_customer', models.IntegerField()),
                ('expenses_shirt', models.IntegerField()),
                ('expenses_tshirt', models.IntegerField()),
                ('expenses_pants', models.IntegerField()),
                ('expenses_shorts', models.IntegerField()),
                ('expenses_shoes', models.IntegerField()),
                ('expenses_sneakers', models.IntegerField()),
                ('imported_brands', models.BooleanField()),
                ('national_brands', models.BooleanField()),
                ('is_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='Usuario que ha creado la cuenta', on_delete=django.db.models.deletion.CASCADE, to='security.Login_Customer')),
            ],
            options={
                'verbose_name': 'Cuestionario Cliente',
                'verbose_name_plural': 'Cuestionarios Clientes',
                'ordering': ('is_date',),
            },
        ),
    ]
