# Generated by Django 2.2.6 on 2019-10-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_customer',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Quiz_Master',
        ),
        migrations.AlterField(
            model_name='login_customer',
            name='email',
            field=models.CharField(max_length=150, verbose_name='Email'),
        ),
        migrations.DeleteModel(
            name='Quiz_Customer',
        ),
    ]
