# Generated by Django 2.2.6 on 2019-10-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_login_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login_customer',
            options={'ordering': ('sname',), 'verbose_name': 'Login Cliente', 'verbose_name_plural': 'Login Clientes'},
        ),
        migrations.AlterModelOptions(
            name='login_partner',
            options={'ordering': ('sname',), 'verbose_name': 'Login de Socio', 'verbose_name_plural': 'Login de Socios'},
        ),
        migrations.RenameField(
            model_name='login_customer',
            old_name='is_active',
            new_name='bis_active',
        ),
        migrations.RenameField(
            model_name='login_customer',
            old_name='timestamp',
            new_name='dtimestamp',
        ),
        migrations.RenameField(
            model_name='login_customer',
            old_name='contrasenia',
            new_name='scontrasenia',
        ),
        migrations.RenameField(
            model_name='login_customer',
            old_name='email',
            new_name='semail',
        ),
        migrations.RenameField(
            model_name='login_customer',
            old_name='name',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='login_partner',
            old_name='is_active',
            new_name='bis_active',
        ),
        migrations.RenameField(
            model_name='login_partner',
            old_name='timestamp',
            new_name='dtimestamp',
        ),
        migrations.RenameField(
            model_name='login_partner',
            old_name='contrasenia',
            new_name='scontrasenia',
        ),
        migrations.RenameField(
            model_name='login_partner',
            old_name='email',
            new_name='semail',
        ),
        migrations.RenameField(
            model_name='login_partner',
            old_name='name',
            new_name='sname',
        ),
    ]
