# Generated by Django 2.2.6 on 2019-10-22 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descripción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, help_text='¿Se puede utilizar esta cuenta o está inactiva?')),
                ('created_by', models.ForeignKey(help_text='Usuario que ha creado la cuenta', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.IntegerField(choices=[(0, 'Egreso'), (1, 'Ingreso')], default=1)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Choose_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_customer', models.IntegerField()),
                ('description', models.CharField(max_length=500, verbose_name='descripcion')),
                ('is_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Clientes',
                'ordering': ('type_customer',),
            },
        ),
        migrations.CreateModel(
            name='Quiz_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cod_quiz', models.IntegerField()),
                ('cod_iso_quiz', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('date', models.DateField(help_text='Fecha del movimiento', verbose_name='Fecha')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Cuenta a afectar', on_delete=django.db.models.deletion.CASCADE, to='flow.Account', verbose_name='Cuenta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Category', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(help_text='Usuario que ha creado la cuenta', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='TransactionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1200, verbose_name='Comentario')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Transaction', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Comentario de la transacción',
                'verbose_name_plural': 'Comentarios de transacciones',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Quiz_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotype', models.IntegerField()),
                ('number_shirt', models.IntegerField()),
                ('number_pants', models.IntegerField()),
                ('number_height', models.IntegerField()),
                ('number_weight', models.IntegerField()),
                ('sex_customer', models.IntegerField()),
                ('expenses_shirt', models.IntegerField()),
                ('expenses_tshirt', models.IntegerField()),
                ('expenses_pants', models.IntegerField()),
                ('expenses_shorts', models.IntegerField()),
                ('expenses_shoes', models.IntegerField()),
                ('expenses_sneakers', models.IntegerField()),
                ('imported_brands', models.BooleanField()),
                ('national_brands', models.BooleanField()),
                ('is_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_customer', to='security.Login_Customer')),
                ('type_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_customer', to='flow.Choose_Customer')),
            ],
            options={
                'verbose_name': 'Cuestionario Cliente',
                'verbose_name_plural': 'Cuestionarios Clientes',
                'ordering': ('is_date',),
            },
        ),
    ]
