# Generated by Django 2.2.6 on 2019-10-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choose_customer',
            name='type_sex',
            field=models.IntegerField(choices=[(0, 'Hombre'), (1, 'Mujer'), (2, 'Otros')], default=1),
        ),
        migrations.AlterField(
            model_name='choose_customer',
            name='is_active',
            field=models.BooleanField(verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='choose_customer',
            name='type_customer',
            field=models.IntegerField(verbose_name='Tipo Cliente'),
        ),
    ]
