# Generated by Django 2.2.6 on 2019-10-22 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_login_partner'),
        ('flow', '0002_auto_20191021_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choose_customer',
            options={'ordering': ('ntype_customer',), 'verbose_name': 'Tipo de Cliente', 'verbose_name_plural': 'Tipos de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='quiz_customer',
            options={'ordering': ('dtimestamp',), 'verbose_name': 'Cuestionario Cliente', 'verbose_name_plural': 'Cuestionarios Clientes'},
        ),
        migrations.AlterModelOptions(
            name='quiz_master',
            options={'ordering': ('sname',), 'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.RenameField(
            model_name='choose_customer',
            old_name='is_active',
            new_name='bis_active',
        ),
        migrations.RenameField(
            model_name='choose_customer',
            old_name='is_date',
            new_name='dtimestamp',
        ),
        migrations.RenameField(
            model_name='choose_customer',
            old_name='description',
            new_name='ndescription',
        ),
        migrations.RenameField(
            model_name='choose_customer',
            old_name='type_customer',
            new_name='ntype_customer',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='imported_brands',
            new_name='bimported_brands',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='national_brands',
            new_name='bnational_brands',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='is_date',
            new_name='dtimestamp',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='biotype',
            new_name='nbiotype',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='expenses_pants',
            new_name='nexpenses_pants',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='expenses_shirt',
            new_name='nexpenses_shirt',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='expenses_shoes',
            new_name='nexpenses_shoes',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='expenses_shorts',
            new_name='nexpenses_shorts',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='expenses_sneakers',
            new_name='nexpenses_sneakers',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='expenses_tshirt',
            new_name='nexpenses_tshirt',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='number_height',
            new_name='nnumber_height',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='number_pants',
            new_name='nnumber_pants',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='number_shirt',
            new_name='nnumber_shirt',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='number_weight',
            new_name='nnumber_weight',
        ),
        migrations.RenameField(
            model_name='quiz_customer',
            old_name='sex_customer',
            new_name='nsex_customer',
        ),
        migrations.RenameField(
            model_name='quiz_master',
            old_name='cod_quiz',
            new_name='ncod_quiz',
        ),
        migrations.RenameField(
            model_name='quiz_master',
            old_name='cod_iso_quiz',
            new_name='scod_iso_quiz',
        ),
        migrations.RenameField(
            model_name='quiz_master',
            old_name='name',
            new_name='sname',
        ),
        migrations.RemoveField(
            model_name='choose_customer',
            name='type_sex',
        ),
        migrations.AddField(
            model_name='choose_customer',
            name='ntype_sex',
            field=models.IntegerField(choices=[(0, 'Hombre'), (1, 'Mujer'), (2, 'Otros')], default=1, verbose_name='Sexo'),
        ),
        migrations.CreateModel(
            name='register_partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname_representative', models.CharField(max_length=300, verbose_name='Nombre Representate')),
                ('sname_company', models.CharField(max_length=300, verbose_name='Nombre Empresa')),
                ('sname_fantasy', models.CharField(max_length=300, verbose_name='Nombre Fantasia de la Empresa')),
                ('snumber_ruc', models.CharField(max_length=11, verbose_name='Numero Ruc')),
                ('sstreet_commercial', models.CharField(max_length=500, verbose_name='Direccion Comercial')),
                ('dtimestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_partner', to='security.Login_Partner')),
            ],
            options={
                'verbose_name': 'Registro Socio',
                'verbose_name_plural': 'Registros de los Socios',
                'ordering': ('sname_company',),
            },
        ),
    ]
